configuration:
  width: 800
  height: 800
  luminosity-label: '%1$.2f fb^{-1} (13 TeV)'
  experiment: "CMS"
  extra-label: "Preliminary"
  root: "results/latest"
  luminosity: 2245.561
  luminosity-error: 0.027
  show-overflow: true
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"

files:
  include: ['TT_files_MuonEG.yml', 'TT_files_MC.yml']

plots:
  include: ['TT_plots_MuEl.yml']

legend:
  position: [0.7, 0.6, 0.91, 0.91]

groups:
  include: ['groups.yml']
